// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using iBookStore.Data;

#nullable disable

namespace iBookStore.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class iBookStoreContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("iBookStore.Models.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DatePublished")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ISBN")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Author = "Gayle Laakmann McDowell",
                            DatePublished = new DateTime(2022, 9, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = " Test Description",
                            ISBN = "0984782869",
                            ImageUrl = "/images/coding.jpg",
                            Language = "English",
                            Price = 139,
                            Title = "Crack the coding Interview"
                        },
                        new
                        {
                            Id = 2,
                            Author = "Imran Al Munyeem",
                            DatePublished = new DateTime(2021, 9, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = " Test Description",
                            ISBN = "0984782862",
                            ImageUrl = "/images/python.jpg",
                            Language = "English",
                            Price = 139,
                            Title = "Python Coding"
                        },
                        new
                        {
                            Id = 3,
                            Author = "Mahmoud Artemi",
                            DatePublished = new DateTime(2020, 9, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = " Test Description",
                            ISBN = "0984782861",
                            ImageUrl = "/images/netcore.jpg",
                            Language = "English",
                            Price = 139,
                            Title = "MVC Dot net core"
                        },
                        new
                        {
                            Id = 4,
                            Author = "Imran Al Munyeem",
                            DatePublished = new DateTime(2021, 9, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = " Test Description",
                            ISBN = "0984782862",
                            ImageUrl = "/images/javascript.jpg",
                            Language = "English",
                            Price = 139,
                            Title = "Advance JavaScript"
                        },
                        new
                        {
                            Id = 5,
                            Author = "Imran Al Munyeem",
                            DatePublished = new DateTime(2022, 9, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = " Test Description",
                            ISBN = "0984782863",
                            ImageUrl = "/images/apitest.jpg",
                            Language = "English",
                            Price = 139,
                            Title = "API Testing"
                        },
                        new
                        {
                            Id = 6,
                            Author = "Imran Al Munyeem",
                            DatePublished = new DateTime(2021, 9, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = " Test Description",
                            ISBN = "0984782864",
                            ImageUrl = "/images/automation.jpg",
                            Language = "English",
                            Price = 139,
                            Title = "Automate Everything"
                        },
                        new
                        {
                            Id = 7,
                            Author = "Mahmoud Artemi",
                            DatePublished = new DateTime(2020, 9, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = " Test Description",
                            ISBN = "0984782865",
                            ImageUrl = "/images/pattern.jpg",
                            Language = "English",
                            Price = 139,
                            Title = "Design Pattern"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
